# Generated by Django 5.0.2 on 2024-03-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_listing_listing_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_date',
        ),
    ]
