# Generated by Django 5.0.2 on 2024-03-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_wonauction_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wonauction',
            name='listing',
        ),
        migrations.AddField(
            model_name='wonauction',
            name='listing_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonauction',
            name='listing_image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonauction',
            name='listing_start_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonauction',
            name='listing_title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
